name = sidebar
description = ein Layout mit sidebar
template = sidebar-layout

;Regions
regions[top] = Top
regions[branding] = Branding
regions[slideshow] = Slideshow
regions[navigation] = Navigation
regions[sidebar] = Sidebar
regions[content] = Content
regions[footer] = Footer

;Styles
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.css
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.no-query.css


